// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGy9x7ZxXnn2srTVNWl21atSQmmcdaulw',
    appId: '1:849097551029:web:0e871e0349fe7060dce2fc',
    messagingSenderId: '849097551029',
    projectId: 'impal-a78d2',
    authDomain: 'impal-a78d2.firebaseapp.com',
    storageBucket: 'impal-a78d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb3PdcYT6oCa-X_RhxDpBBFo64WZt1oRg',
    appId: '1:849097551029:android:397e6a309eb8f317dce2fc',
    messagingSenderId: '849097551029',
    projectId: 'impal-a78d2',
    storageBucket: 'impal-a78d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUqvZa01AeDbPuvnDRF4BFnrl-0rgRDxw',
    appId: '1:849097551029:ios:c7219d2ec3da7d50dce2fc',
    messagingSenderId: '849097551029',
    projectId: 'impal-a78d2',
    storageBucket: 'impal-a78d2.firebasestorage.app',
    iosBundleId: 'com.example.nutriguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUqvZa01AeDbPuvnDRF4BFnrl-0rgRDxw',
    appId: '1:849097551029:ios:c7219d2ec3da7d50dce2fc',
    messagingSenderId: '849097551029',
    projectId: 'impal-a78d2',
    storageBucket: 'impal-a78d2.firebasestorage.app',
    iosBundleId: 'com.example.nutriguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGy9x7ZxXnn2srTVNWl21atSQmmcdaulw',
    appId: '1:849097551029:web:15bd430884533f26dce2fc',
    messagingSenderId: '849097551029',
    projectId: 'impal-a78d2',
    authDomain: 'impal-a78d2.firebaseapp.com',
    storageBucket: 'impal-a78d2.firebasestorage.app',
  );
}
